### ISSUE TITLE
Allow comparison to non age-qualifying standards

### ISSUE THREAD

**Issue by cptcanuck** [htmfilho/geekswimmers#13]
Kids may we want to be able to compare their times to standards they don't yet qualify for - for example, I think OYJs are technically for 13+, but some kids may want to look and see where they stack up.   I also think that if a child younger than OYJ age qualifies, they are allowed to go

It would be interesting if there could be a 'compare against all standards for closest age' checkbox to show how close/far the swimmer is to those other standards. 

I think you could get the min() value for age from the DB, then search against that qualifying age, and return the results?

**Comment by htmfilho** [comment]
I think it's already implemented. It is in the `meet` table because it is a meet-specific requirement. Now, the question is, did you find a bug?

**Comment by cptcanuck** [comment]
Using someone born in 2012 for example, they only show up with WOSA and Festivals in the UI, which makes sense as the min_age is 10 for those, max_age is 12.  however, I'd like to see if a 2012 swimmer has a time that qualifies for OYJ standards, with a min_age of 13.  is the 'min_age_enforced' or 'max_age_enforced' important in that query, or is that tied to other logic?

**Comment by htmfilho** [comment]
You can actually see OYJ for 11 years old. It is configured as 13&Under. You probably selected short course, while all OYJs are long course.

![Screenshot from 2024-01-29 08-29-23](https://github.com/htmfilho/geekswimmers/assets/200272/fdd3c7e3-fb63-4920-bbeb-2b2b53d563e0)

**Comment by cptcanuck** [comment]
I think the Winter standard should be for SCM?    The standard has SCM (https://admin.swimontario.com//documents/317/SwimON_2023-2024_Championships_Standards_-_OYJ.pdf) and the meet (https://www.swimontario.com/athletes/competitions/2024-winter-ontario-youth-junior-championships/) says it is SCM as well as LCM.  That's confusing, but :shrug?

**Comment by htmfilho** [comment]
Strange. The meet package is indicating that the February one is a Long Course meet. Maybe, the meet is LCM but LCM and SCM can qualify? Oh gosh! So complicated. :(

**Comment by cptcanuck** [comment]
It might be a weirdity of swimming - for example, my daughter qualified for SC festivals based on her converted LC festival times in the summer.  So converted LCM can be used for SCM meet qualifiers.  that's a whole new can of worms for ya :S
