### ISSUE TITLE
Support club records in addition to time standards

### ISSUE THREAD

**Issue by htmfilho** [htmfilho/geekswimmers#14]
We may need to think if "club records" can be considered as time standards, reusing the current implementation, or as its own entities like "club" and "club-records". A club records table may look like the time standards table, but we may allow clubs to update their own club records in the future, without letting them have access to the time standards.

**Comment by cptcanuck** [comment]
I wonder if we could build something magical by using swimrankings which has the records for all clubs, and make it a dynamic fetch (in the future) - if we don't have the record, we could bring it in and cache it, or have a process that brings it the records and puts them into a table (but then we have to be worried about pollution, table sizes growing, etc)

**Comment by cptcanuck** [comment]
it looks like putting in records as 'standards' might be a hacky solution - wondering if you make each age a 'standard' to simplify the UI, set the min_age/max_age to the same value for the one year?

I can do a quick pass and create a single year age and give it a try - does your deployment CI do the database migrations/loads automatically, or is that a manual step for you (ie: is testing this a PITA, or relatively easy?)

I know the kids in PD2 are all really keen on tracking against the club records,which is why it's on my mind :)  I'm happy to leave it to the future, and try and pickup somethign else while you think this through.

**Comment by cptcanuck** [comment]
ahh I see a challenge - standards are tied to `swim_season` - so there'd need to be something like 'all seasons' or similar.

**Comment by cptcanuck** [comment]
intersting - you can directly export an XLS file with the right parameters passed:

https://www.swimrankings.net/services/RankingXls/ranking.xls?gender=F&agegroup=11011&course=SCM&season=-1&clubId=72376&Points=fina_2023&Language=us

**Comment by htmfilho** [comment]
I agree it would be a hack solution. If we adopt time_standards for records, we may have several columns that do not apply for records and vice-versa, forcing us to put too many conditions in the code. 

I'm inclined to create separate tables for records in general and organize them by jurisdiction and age. Example:
- world records
- Canadian records
- provincial records
- regional records ?
- club records
- meet records

Then we would have tables for:
- countries 
- provinces
- regions ?
- clubs
- meets (already exists)

The migration runs automatically by the application after a successful deployment. We need to "play" a lot before pushing to `main`. Continuous delivery.

We can start doing the records now. Let's just put some thought here so it can last longer and for more scenarios. At the beginning, I thought the standards would be straightforward, but the custom criteria for each meet made it harder. It might be the same for records.

**Comment by htmfilho** [comment]
It may need database changes. Here is the current relational model: https://www.hildeberto.com/geekswimmers/

**Comment by htmfilho** [comment]
![records](https://github.com/htmfilho/geekswimmers/assets/200272/c7e6bbab-1aaf-4f25-bf51-84ce84508e6b)

- When `record` has no `scope` then it is a world record.
- For a country record, only the `country` field is informed in `record_scope`
- For a provincial record, `country` and `province` are informed in `record_scope`
- For a regional record, `country`, `province` and `region` are informed in `record_scope`
- In the `record` table, only `scope` is not required
- In the `record_scope` table, only `country` is required
- In the `record_time` table, only `taken_time` is required
