### ISSUE TITLE
Provide deep link to result

### ISSUE THREAD

**Issue by cptcanuck** [htmfilho/geekswimmers#21]
Provide the ability to link to a result 

In addition to general usefulness, this could also be used to create a 'Share to Facebook|Instagram' function so people could share their accomplishment :)

**Comment by htmfilho** [comment]
Can you clarify "deep link" and how it is supposed to work? Do you mean, supporting a URL that would contain all search criteria to get the result, so we can share this link with others so they can see the same result without filling in the search form?

**Comment by htmfilho** [comment]
Hi @cptcanuck , I'm planning to work on it soon. Can you confirm or fix my interpretation of you request? Thanks.
