### ISSUE TITLE
Add support for content publishing

### ISSUE THREAD

**Issue by htmfilho** [htmfilho/geekswimmers#24]
The creation of GeekSwimmers have a very curious story that needs to be told. To do that, we want to create a blog. We evaluated many options available out there but all of them required some compromise. So, we decided to build it right into the app to have full control over our requirements and reduce hosting costs.

We will create a table to store content in markdown format, convert the markdown to html in the controller, and serve the resulting html content. If the performance disappoint us, we will save the html into the same table, right after the first request to that content, and serve it from the second request forward.

Images referenced by the content will be stored in the `web/static/images` folder.

**Comment by cptcanuck** [comment]
in case it helps, I've used this before to build content for workshops - https://gohugo.io/.  Markdown based, simple image inclusion.  $0.02

**Comment by htmfilho** [comment]
I will check if it is possible to integrate it somehow. Using it as-is would require a separate hosting.
