### ISSUE TITLE
Store birthday and gender across sessions?

### ISSUE THREAD

**Issue by cptcanuck** [htmfilho/geekswimmers#9]
Could you add a way (cookie) to keep the birthday/gender between sessions, to minimize re-typing?

**Comment by htmfilho** [comment]
Yes, we can. I agree that typing that date is not fun. In this case, we also need to put the dialog to ask the user to accept cookies. We can only save the birthday and the gender in the session if the user agrees.

We can keep the session valid for a while (I would say a month) so the user doesn't have to accept it all the time.

**Comment by cptcanuck** [comment]
oh cool, thats handy (with the session) and would smooth things out 100%

**Comment by htmfilho** [comment]
I have the implementation in another personal project. I will assign this one to myself and start now because we may need it for the records search too (#14).

**Comment by htmfilho** [comment]
Taking all this into account in the solution: 

1. Implement an API endpoint that can accept calls from the UI to activate the use of cookies by creating an encrypted one.
2. Ask the user through a dialog to confirm they want to use cookies. If they want, call the API endpoint with their decision. Use their decision to hide the dialog.
3. If we have a `sessionKey` set in the configuration and the user wants to use cookies then save the selected date of birth and the gender in the session.
4. At every form submission, check if the user changed the date of birth and gender and update the session if they did.
